name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 3.0.1
      - name: Install dependencies
        run: bundle install
      - name: Run rubocop
        run: bundle exec rubocop
      - name: Run tests
        run: bundle exec rspec spec/*
